{{- if .Values.ingress.create -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: {{ include "app.name" . }}-https
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ include "app.name" . }}.{{ .Values.ingress.domain }}-ssl
    options:
      name: tlsoptions
      namespace: kube-system
  routes:
  - match: Host(`{{ .Values.ingress.hostname }}.{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: console
      port: 9090
{{- end -}}
